# -*- coding: utf-8 -*-
"""Prj_702_RQ3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q2HI__Mpwm6fWwAs0UuUgBhfSNpUPSPm
"""

# === Suppress Warnings ===
import warnings
warnings.filterwarnings('ignore')

# === STEP 1: Import libraries ===
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid", font_scale=1.1)
plt.rcParams['figure.figsize'] = (12, 6)

# === STEP 2: Manually recreate the dataset (or load from CSV) ===
data = {
    "family_group": [
        "4+ members (≥2+ children)", "3 members (one child)", "3 members", "3 members (one child)",
        "4+ members (≥2+ children)", "2 members", "2 members", "2 members", "3 members (one child)",
        "1 member", "4+ members (≥2+ children)", "2 members", "3 members (one child)", "1 member",
        "1 member", "1 member", "4+ members (≥2+ children)", "3 members (one child)",
        "4+ members (≥2+ children)", "Unknown", "4+ members (≥2+ children)", "3 members (one child)",
        "2 members", "1 member", "1 member", "4+ members (≥2+ children)", "3 members (one child)",
        "3 members (one child)", "2 members", "2 members", "1 member", "1 member"
    ],
    "income_level": [
        "Unknown", "Unknown", "Unknown", "Middle", "Middle", "High", "Middle", "High", "High", "Unknown",
        "Low", "Low", "Low", "High", "Middle", "Low", "Unknown", "Unknown", "Middle", "Unknown", "High",
        "Middle", "Middle", "Middle", "High", "Low", "High", "High", "Low", "High", "Unknown", "Low"
    ],
    "is_weekend": [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    ],
    "orders": [
        26406, 20680, 19386, 18421, 14687, 11002, 11258, 4916, 5742, 4147,
        3026, 2672, 2223, 1945, 1516, 1512, 80, 76, 74, 65, 39, 40, 40, 5,
        6, 24, 21, 6, 13, 16, 13, 3
    ],
    "total_sales_amount": [
        186437083.0, 134685978.0, 128937967.0, 102923588.0, 93184397.0, 71748838.0, 69968231.0, 35484316.0,
        35477888.0, 31683489.0, 21708479.0, 18891828.0, 16363048.0, 15354820.0, 9768181.0, 9394837.0,
        428576.0, 299840.0, 273546.0, 181940.0, 108637.0, 88774.0, 71947.0, 47338.0, 39408.0, 28349.0,
        27746.0, 27740.0, 23782.0, 6568.0, 5864.0, 977.0
    ],
    "AOV": [
        6303.0, 6513.36, 6697.51, 6874.85, 6340.6, 6518.67, 6214.09, 7218.13, 6178.66, 7635.82,
        7172.28, 7070.29, 7360.8, 7894.23, 6439.41, 6213.52, 5357.2, 3940.86, 3696.57, 2799.08,
        2785.6, 1775.48, 1793.67, 9467.6, 6568.0, 2577.18, 1321.24, 4623.35, 1824.77, 410.5,
        428.0, 326.67
    ]
}

df = pd.DataFrame(data)

# === STEP 3: Plot AOV vs Family + Income group ===
plt.figure(figsize=(14, 7))
sns.barplot(data=df[df['is_weekend'] == 0], x="family_group", y="AOV", hue="income_level", palette="Set2")
plt.title("Average Order Value by Family Group and Income Level (Weekdays)", fontsize=14)
plt.xticks(rotation=25, ha='right')
plt.ylabel("AOV (INR)")
plt.xlabel("Family Group")
plt.tight_layout()
plt.legend(title="Income Level", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

print("\n💡 Insight:\nOn weekdays, larger families (especially 4+ with children) and high-income groups \
show significantly higher average order value (₹6300–₹7900+), indicating bulk or premium consumption behavior.\n")

# === STEP 4: Compare AOV Distribution (Weekend vs Weekday) ===
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x="is_weekend", y="AOV", palette="coolwarm")
plt.xticks([0, 1], ["Weekday", "Weekend"])
plt.title("AOV Comparison: Weekend vs Weekday", fontsize=14)
plt.ylabel("AOV (INR)")
plt.xlabel("Day Type")
plt.tight_layout()
plt.show()

print("\n💡 Insight:\nAOV is generally **lower on weekends**, possibly due to more frequent, smaller-value casual purchases.\n")

# === STEP 5: Save visualization files (optional) ===
# plt.savefig("/mnt/data/family_income_AOV.png", dpi=200, bbox_inches='tight')

# === Suppress Warnings ===
import warnings
warnings.filterwarnings('ignore')

# === STEP 1: Import Libraries ===
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid", font_scale=1.1)
plt.rcParams['figure.figsize'] = (12, 6)

# === STEP 2: Sample DataFrame (replace this with your actual CSV import) ===
# Only showcasing a subset for illustration – expand as needed from full dataset
data = {
    "family_group": ["4+ members (≥2+ children)", "3 members (one child)", "3 members", "3 members (one child)"] * 2,
    "income_level": ["Unknown", "Unknown", "Unknown", "Middle"] * 2,
    "is_holiday": [0, 0, 0, 0, 1, 1, 1, 1],
    "orders": [26389, 20606, 19388, 15375, 187, 130, 113, 96],
    "total_sales_amount": [186165810.0, 133663846.0, 128539740.0, 102589683.0, 710098.0, 900092.0, 481967.0, 428679.0],
    "AOV": [6310.74, 6501.28, 6698.68, 6670.55, 4828.92, 6923.78, 4266.19, 4716.41]
}
df = pd.DataFrame(data)

# === STEP 3: AOV by Family Group and Holiday Flag ===
plt.figure(figsize=(14, 6))
sns.barplot(data=df, x="family_group", y="AOV", hue="is_holiday", palette="Set1")
plt.title("AOV by Family Group: Holiday vs Non-Holiday", fontsize=14)
plt.ylabel("Avg Order Value (INR)")
plt.xlabel("Family Group")
plt.xticks(rotation=20)
plt.legend(title="Is Holiday", labels=["No", "Yes"])
plt.tight_layout()
plt.show()

print("\n🎯 Insight:\nDuring holidays, AOV for some family types (e.g., smaller or middle-income) may decline,\n\
indicating more budget-conscious or fragmented purchases. Larger families continue to spend in bulk.\n")

# === STEP 4: AOV by Income Level and Holiday Flag ===
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x="income_level", y="AOV", hue="is_holiday", palette="muted")
plt.title("AOV Distribution by Income Level (Holiday vs Non-Holiday)", fontsize=14)
plt.ylabel("Avg Order Value (INR)")
plt.xlabel("Income Level")
plt.xticks(rotation=15)
plt.legend(title="Is Holiday", labels=["No", "Yes"])
plt.tight_layout()
plt.show()

print("\n📊 Observation:\nIncome level correlates with spending ability.\n\
During holidays, low-income households show more variation in AOV, possibly indicating need-based spending.\n")